Add FileLockUtils (from platform/download-service)
ridibooks/platform-common pull request #19
Opened 2019-02-15 09:43 UTC by iiogmgo

기존 download-service에 구현되어있던 file lock 관련 코드 부분을 분리하였습니다.

- download-service 외 플랫폼 프로젝트에서 이용하기 위함
- ridibooks/core의 fileLock 사용을 위해 core 전체를 참조하기에는 오버스펙으로 판단

2019-02-15 10:17 UTC, ssaifriend requested changes

2019-02-15 10:17 UTC, ssaifriend commented on lib/FileLockUtils.php
> +        $this->lock_file = fopen($this->lock_file_name, 'w+');
`fopen` 의 return type은 `resource` 입니다. `chmod` 코드가 아마 동작하지 않을 것 같네요~
원래 코드가 이랬다면, 버그로 보입니다!

2019-02-15 10:17 UTC, ssaifriend commented on lib/FileLockUtils.php
> +    public function releaseLock()
`__destruct` 를 걸어놓으면 어떨까요?

2019-02-15 11:33 UTC, namenu requested changes
기존에 있던 코드라 리뷰를 드리지 않으려 했는데, 잘못을 반복하는 것은 더 나쁘다는 생각이 들어서 코멘트 남깁니다.

2019-02-15 11:33 UTC, namenu commented on lib/FileLockUtils.php
> +            $elapsed_ms += $timeout_resolution;
@iiogmgo 원래 코드도 이랬겠지만, `$elapsed_ms` 는 아래의 usleep 이후에 변경되는 것이 올바른 구현 같습니다.

2019-02-15 11:33 UTC, namenu commented on lib/FileLockUtils.php
> +    private function tryByType(bool $is_exclusive): bool
함수 이름에 type이라는 키워드가 있는데 정작 인자는 read/write로 표현되지 않는 불일치가 있습니다.
`tryLock` 정도로 바꾸는 것이 어떨까요?

2019-02-15 11:33 UTC, namenu commented on lib/FileLockUtils.php
> +    protected $lock_file_name;
protected 일 이유가 없어 보입니다.

2019-02-18 04:59 UTC, iiogmgo commented on lib/FileLockUtils.php
> +        $this->lock_file = fopen($this->lock_file_name, 'w+');
chmod는 $this->lock_file_name 을 인자로 받습니다. chmod 실행되는 것으로 보입니다.

2019-02-18 05:15 UTC, ssaifriend approved these changes

2019-02-18 10:24 UTC, namenu approved these changes

2019-02-20 04:41 UTC, merged