add services for S3 and Sqs in AWS
ridibooks/platform-common pull request #22
Opened 2019-09-19 10:39 UTC by Goliathtom

2019-09-19 11:37 UTC, ssaifriend requested changes

2019-09-19 11:37 UTC, ssaifriend commented on lib/AWS/SqsService.php
> +class SQSUtils extends AbstractAwsService
class이름과 파일명이 안 맞아요.

2019-09-19 11:37 UTC, ssaifriend commented on lib/AWS/Dto/AwsConfigDto.php
> +    public static function importFromKeys(
AccessKey가 좀 더 명확하지 않을까요?

2019-09-20 00:30 UTC, Goliathtom commented on lib/AWS/SqsService.php
> +class SQSUtils extends AbstractAwsService
오마이갓...

2019-09-20 12:36 UTC, ssaifriend approved these changes

2019-09-23 10:01 UTC, merged