Dependency update
ridibooks/platform-common pull request #29
Opened 2020-04-07 09:18 UTC by ssaifriend

## 변경점
- `sentry/sentry` , `monolog/monolog` 업데이트
- `symfony/http-foundation` 5.x 최저 버전 설정 (보안 이슈)
- `ridibooks/core` suggest 제거
- Deprecated 된 class들의 내용 삭제 및 오류 발생 활성화

## 기타
- 이번 배포시 1.0으로 배포 할 예정입니다. 이제 올릴 때가 된 것 같네요.
- SentryClient 들 활성화 하는 방법이 계속 고민되는데요, 주의깊게 확인 부탁드립니다.

2020-04-13 04:36 UTC, kiding commented on lib/Sentry/SentryHelper.php
> +    public const DEFAULT_RAVEN_CLIENT_NAME = '__RAVEN_CLIENT';
[raven-php](https://github.com/getsentry/raven-php)가 [sentry-php](https://github.com/getsentry/sentry-php)로 변경되면서 "Raven"이라는 이름을 더이상 사용하지 않고 있습니다.

`SentryHelper`에서도 `DEFAULT_RAVEN_CLIENT_NAME`과 `$raven_client_name`이 사용되지 않으므로 삭제하는 것이 좋을 것 같습니다.

2020-04-14 00:58 UTC, ssaifriend commented on lib/Sentry/SentryHelper.php
> +    public const DEFAULT_RAVEN_CLIENT_NAME = '__RAVEN_CLIENT';
실제로 사용하진 않지만, 코드 호환성때문에 남겨둔거에요.
기존과 동일한 class/method 명을 유지해서 업데이트시 코드 작업을 없게하기 위함입니다.

2020-04-14 01:15 UTC, kiding commented on lib/Sentry/SentryHelper.php
> +    public const DEFAULT_RAVEN_CLIENT_NAME = '__RAVEN_CLIENT';
그렇군요! `@deprecated` 표시를 해주면 좋을 것 같다는 생각이 드는데, `const`의 경우는 쉽게 가능하지만 메소드 파라미터의 경우에는 [지원되지 않는 같네요](https://stackoverflow.com/q/27005219)...

2020-04-17 06:29 UTC, kobi97 approved these changes

2020-04-20 05:11 UTC, Goliathtom approved these changes

2020-04-20 05:36 UTC, kiding commented on lib/Sentry/SentryHelper.php
> +        SentryClient::init($sentry_key, [], $error_types);
`SentryHelper::enableSentry()`와 `SentryHelper::overrideSentry()`에서 `SentryClient::init()`을 직접 부르고 있습니다. `LumenSentryClient` 또는 추후에 추가될 어떤 `SentryClientInterface`를 사용하고자 하는 경우 이 메소드 두개를 부르지 않도록 유도하는 게 바람직할 것 같습니다.

`SentryHelper`를 옮겨오기 이전 실행되던 코드는 `SentryClientInterface::init()`으로 이전되어 여기 두 메소드는 `@deprecated` 처리할 수 있을 것 같은데, 어떻게 생각하시는지요?

2020-04-20 05:46 UTC, ssaifriend commented on lib/Sentry/SentryHelper.php
> +        SentryClient::init($sentry_key, [], $error_types);
위 `SentryHelper` 에 남겨주신 코멘트와 유사한 유형으로 판단되는데요,
이 method를 남겨둔거는 동일하게 호환성때문입니다. 나중에 이 method는 사용처들을 모두 교체하고 삭제할 예정입니다.

2020-04-20 06:01 UTC, kiding commented on lib/Sentry/SentryHelper.php
> +        SentryClient::init($sentry_key, [], $error_types);
그렇군요. 아무래도 말씀하신 내용을 코드만 봐서는 알기 어렵다보니 라이브러리 사용자 입장에서 혼란이 있을 수 있겠다는 코멘트였습니다.

2020-04-20 09:33 UTC, kiding commented on lib/Sentry/SentryHelper.php
> +            $response = captureMessage($formatted_message, $level);
`$params`로 추가 데이터가 전달되는 경우 Sentry에 기록되지 않는 문제가 있습니다.

#### 영향을 받는 부분
* [`[every]multi_book_processor.php`](https://gitlab.com/ridicorp/platform/admin/-/blob/aa3b7d29/cron/%5Bevery%5Dmulti_book_processor.php#L45) 
* [`AjaxController::triggerSentryMessage()`](https://gitlab.com/ridicorp/platform/cp/-/blob/ea724752/src/Ridibooks/Cp/Controller/AjaxController.php#L82)

#### 테스트 코드
```php
SentryHelper::triggerSentryMessage('메시지', ['Apple', 'Banana', 'Cat']);
```

##### 이전 (`0.21.1`)

<img width="808" alt="image" src="https://user-images.githubusercontent.com/1336881/79736621-10685600-8335-11ea-9bd1-9e6e4b0963cd.png">

##### 이후 (`improve/update_sentry`)

<img width="798" alt="image" src="https://user-images.githubusercontent.com/1336881/79736842-63daa400-8335-11ea-8400-0cffaabcc2a0.png">

2020-04-20 10:40 UTC, kiding requested changes
Monolog 연동 부분 확인하려니 Sentry SDK 쪽 문서에 문제가 많네요 😭 수고가 많으셨습니다.

2020-04-21 03:32 UTC, ssaifriend commented on lib/Sentry/SentryHelper.php
> +            $response = captureMessage($formatted_message, $level);
로그레벨을 바꾼건 의도한겁니다. 흠.. message param 넘기는건 좀 봐야겠군요

2020-04-21 05:57 UTC, ssaifriend commented on lib/Sentry/SentryHelper.php
> +            $response = captureMessage($formatted_message, $level);
좀 테스트를 해봤는데, 이제 더 이상 지원 안하는 기능이네요 🤦

2020-04-21 06:00 UTC, ssaifriend commented on lib/Sentry/SentryHelper.php
> +        SentryClient::init($sentry_key, [], $error_types);
`@deprecated` doc 추가했습니다

2020-04-21 06:06 UTC, kiding commented on lib/Sentry/SentryHelper.php
> +            $response = captureMessage($formatted_message, $level);
```php
// vsprintf에서 포매팅이 일어나지 않은 경우 $params를 extra 데이터로 가정
if ($formatted_message === $message) {
    $scope->setExtras($params);
}
```
같은 느낌으로 전달할 수 있을... 것 같습니다.

2020-04-21 06:08 UTC, ssaifriend commented on lib/Sentry/SentryHelper.php
> +            $response = captureMessage($formatted_message, $level);
object(key=>value) 형태가 아니면 오류가 뜬답니다 🤦 
![image](https://user-images.githubusercontent.com/1916350/79831227-f6388180-83e1-11ea-9ecc-e4d54cc68569.png)

2020-04-21 06:45 UTC, kiding commented on lib/Sentry/SentryHelper.php
> +            $response = captureMessage($formatted_message, $level);
```php
if ($formatted_message === $message) {
    $scope->setExtras($params + ['' => '']);
}
```

이렇게 했더니 강제로 딕셔너리로 인식해서 (= 내부에서 사용하는 json_encode의 결과가 object여서) 일단 오류 없이... 동작하네요...
<img width="417" alt="image" src="https://user-images.githubusercontent.com/1336881/79833678-c0e26280-83e6-11ea-841c-9ed88d37d600.png">

2020-04-21 10:12 UTC, ssaifriend commented on lib/Sentry/SentryHelper.php
> +            $response = captureMessage($formatted_message, $level);
어렵군요 흠... 일단 extra - params 로 할께요

2020-04-21 11:21 UTC, kiding commented on lib/Sentry/SentryHelper.php
> +            $response = captureMessage($formatted_message, $level);
`mt_rand()`가 좀 찝찝하긴 하지만... 거의 호출될 일이 없으니 괜찮겠...죠? 

저희 코드 베이스에 `$level_or_options` 파라미터까지 사용하는 경우 자체가 없는 덕분에 key가 겹쳐서 문제가 생길 여지도 거의 없을 것 같습니다.

2020-04-21 11:23 UTC, ssaifriend commented on lib/Sentry/SentryHelper.php
> +            $response = captureMessage($formatted_message, $level);
혹시 몰라서 넣어둔거라 ~_~..ㅎㅎ

2020-04-21 11:30 UTC, kiding commented on lib/Sentry/SentryHelper.php
> +        string $message,
string 타입으로 강제되어 있어 오류가 발생할 수 있는 부분이 있습니다.
* [`manageSerialSeries.action.php `](https://gitlab.com/ridicorp/platform/admin/-/blob/6aec3647/controls/book/manageSerialSeries.action.php#L28)
* [`CpNoticeRequestService::approveBookNoticeByRequest()`](https://gitlab.com/ridicorp/platform/php-src/-/blob/93a0487f/src/Ridibooks/Platform/CpAdmin/CpNoticeRequestService.php#L383)
...

2020-04-22 00:32 UTC, ssaifriend commented on lib/Sentry/SentryHelper.php
> +        string $message,
구두로 말씀드렸다싶이, 이건 사용하는쪽이 잘못사용하고 있는 것이라 사용처를 수정하겠습니다.

2020-04-22 01:28 UTC, kiding approved these changes

2020-04-22 01:58 UTC, merged