add cron master util
ridibooks/platform-common pull request #8
Opened 2017-09-27 08:55 UTC by kobi97

cron master를 util화 하기 위한 첫단계로 platform-common으로 이동하도록 이야기가 진행되어 리뷰 완료 후 PR 올립니다.

2017-10-10 03:12 UTC, genesos requested changes
composer 참조 확인 필요

2017-10-10 03:12 UTC, genesos commented on lib/Cron/CronMaster.php
> +use Ridibooks\Exception\MsgException;
@ssaifriend 
지금보니 MsgException 이거 "ridibooks/store"의 MsgException를 참고하는것 같은데,
지금 composer 참조상으로는 없네요. 어떻게 하면 좋을까용?

2017-10-10 04:48 UTC, kobi97 commented on lib/Cron/CronMaster.php
> +use Ridibooks\Exception\MsgException;
@genesos @ssaifriend MsgException이 core에 있는게 아니고, store에 있었네요 -_-;;  Ridibooks\Platform\Common\Exception\CommonException을 하나 추가하는 것은 어떠신가요?

2017-10-10 05:10 UTC, genesos commented on lib/Cron/CronMaster.php
> +use Ridibooks\Exception\MsgException;
넵 전 그게 좋을것 같습니다!!
해당방법이 선택되면 다른 MsgException도 플랫폼팀걸 쓰도록 하시지용 ㅎㅎ

2017-10-11 05:42 UTC, ssaifriend commented on lib/Cron/CronMaster.php
> +use Ridibooks\Exception\MsgException;
저도 동의합니다~!

2017-10-12 01:46 UTC, kobi97 commented on lib/Cron/CronMaster.php
> +use Ridibooks\Exception\MsgException;
@genesos @ssaifriend 코드를 쭈욱 확인해보았는데요. 이미 다른 Utils들에서 store의 MsgException들을 사용하고 있고, JsonDto 같은 경우 Ridibooks/Exception/MsgException에 의존성이 있어서, 새롭게 만들면 2개의 MsgException을 처리해야 합니다. 그리고 다시 store가 플랫폼팀 코드를 사용하게 되면 MsgException이 2개라서 문제의 소지가 있어 보입니다. ssaifriend과 이야기해보았는데, store에 요청해서 MsgException을 core에 옮기는 요청을 보내기로 결론 내렸습니다.

2017-10-12 01:48 UTC, kobi97 commented on lib/Cron/CronMaster.php
> +use Ridibooks\Exception\MsgException;
따라서 해당 merge는 이대로 진행해도 될 것 같습니다.

2017-10-12 06:11 UTC, genesos approved these changes

2017-10-12 06:18 UTC, ssaifriend approved these changes

2017-10-12 10:08 UTC, namenu commented
https://gitlab.ridi.io/common/php-core/blob/master/CHANGELOG

참고 바랍니다.

2017-10-12 10:27 UTC, kobi97 commented
@namenu 넵 참고해서 적용하겠습니다.

2017-10-13 02:24 UTC, merged